# Generated by Django 4.2.6 on 2023-10-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AkaliAlimentosApp', '0004_cart_carttoproduct_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.CharField(default='assets/img/icono_placeholder.png', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default='Producto de Akali Alimentos', max_length=40),
        ),
    ]
