# Generated by Django 4.2.6 on 2023-10-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AkaliAlimentosApp', '0006_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.CharField(default='assets/img/icono_placeholder.png', max_length=150),
        ),
    ]
