# Generated by Django 4.2.6 on 2023-10-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AkaliAlimentosApp', '0007_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.CharField(default="{% static 'assets/img/icono_placeholder.png' %}", max_length=150),
        ),
    ]
