# Generated by Django 4.2.6 on 2023-10-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AkaliAlimentosApp', '0008_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.CharField(max_length=20),
        ),
    ]
