# Generated by Django 4.2.6 on 2023-10-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AkaliAlimentosApp', '0009_alter_user_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
