# Generated by Django 4.2.6 on 2023-10-31 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AkaliAlimentosApp', '0017_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carttoproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='carttoproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartToProduct',
        ),
    ]
