# Generated by Django 4.2.6 on 2023-10-31 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AkaliAlimentosApp', '0018_remove_carttoproduct_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CartToProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AkaliAlimentosApp.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AkaliAlimentosApp.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='productlist',
            field=models.ManyToManyField(related_name='productlist', to='AkaliAlimentosApp.carttoproduct'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
