# Generated by Django 4.2.6 on 2023-11-24 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AkaliAlimentosApp', '0021_remove_order_products_remove_ordertoproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertoproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='AkaliAlimentosApp.order'),
        ),
    ]
