# Generated by Django 4.2.6 on 2023-11-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AkaliAlimentosApp', '0022_alter_ordertoproduct_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=99999, max_digits=14),
            preserve_default=False,
        ),
    ]
